In [256]:
import pandas as pd

In [257]:
dataset=pd.read_csv("RetailDataset.csv")

In [258]:
print(dataset.to_string())

         Product     Category  Customer     Region        Date  Quantity  Unit Price  Discount    Cost      Sales
0        Printer  Electronics  Cust_440     Canada  18-03-2023         8         733      0.17  1153.0    4867.12
1        Printer       Office  Cust_480     Canada  01-08-2024         4        1998      0.29   499.0    5674.32
2            NaN  Electronics  Cust_205         UK  22-10-2024         8        1470      0.22  1040.0    9172.80
3        Monitor  Electronics  Cust_336         UK  21-08-2023         5         214      0.08   753.0     984.40
4        Monitor  Accessories  Cust_440     Canada  17-10-2022         4         213      0.01   637.0     843.48
5     Headphones  Accessories  Cust_138     Canada  10-01-2023         7        1751      0.25   633.0    9192.75
6         Tablet  Accessories  Cust_457        USA  20-12-2024         6         118      0.26   241.0     523.92
7          Mouse       Office  Cust_193    Germany  15-06-2022         2        1703      0.27   877.0    2486.38
8          Phone  Electronics  Cust_194         UK  21-06-2022         4         932      0.15  1298.0    3168.80
9     Headphones  Electronics  Cust_464    Germany  16-12-2024         2         248      0.10   242.0     446.40
10      Keyboard  Accessories   Cust_72  Australia  29-03-2023         4         469      0.07  1465.0   17446.80
11      Keyboard  Electronics  Cust_161    Germany  13-07-2022         4        1005      0.24   391.0    3055.20
12       Printer  Electronics  Cust_494      India  13-12-2024         3        1774      0.12  1238.0    4683.36
13      Keyboard       Office  Cust_115        USA  31-07-2023         1         430      0.16     NaN     361.20
14        Laptop  Electronics  Cust_371      India  20-03-2023         5        1012      0.07  1207.0    4705.80
15        Tablet       Office   Cust_29         UK  14-09-2023         2          63      0.08   938.0     115.92
16        Laptop  Electronics  Cust_289        USA  11-03-2023         2         674      0.29  1463.0     957.08
17      Keyboard  Electronics  Cust_355     Canada  14-01-2023         7         648      0.14   649.0    3900.96
18         Phone  Accessories  Cust_382  Australia  16-05-2022         7         178      0.01  1151.0    1233.54
19        Laptop  Accessories  Cust_452  Australia  03-07-2023         5        1241      0.23   442.0    4777.85
20       Printer  Accessories  Cust_106      India  21-04-2024         9         850      0.20    98.0    6120.00
21       Printer       Office   Cust_76  Australia  29-11-2022         3         801      0.07  1322.0    2234.79
22        Tablet  Electronics  Cust_386        USA  30-04-2024         9         474       NaN   830.0    3284.82
23    Headphones       Office  Cust_434    Germany  16-08-2022         7        1052      0.29   858.0    5228.44
24       Printer  Accessories  Cust_377         UK  21-04-2023         6        1636      0.27  1339.0    7165.68
25        Laptop  Accessories  Cust_360         UK  12-09-2022         8        1202      0.22  1426.0    7500.48
26        Tablet  Accessories  Cust_323    Germany  13-09-2023         1        1624      0.03  1226.0    1575.28
27        Laptop       Office   Cust_54     Canada  06-02-2024         1         985      0.10   205.0     886.50
28        Tablet  Accessories   Cust_61        USA  16-05-2023         7         856      0.25   887.0    4494.00
29       Printer  Electronics  Cust_109    Germany  01-07-2024         1        1678      0.18   486.0    1375.96
30         Phone       Office  Cust_175     Canada  12-12-2022         3         157      0.24   539.0     357.96
31    Headphones  Accessories  Cust_169      India  03-11-2022         8        1394      0.01   409.0   11040.48
32       Printer  Accessories  Cust_146      India  10-01-2023         8         912      0.18   251.0    5982.72
33    Headphones  Electronics  Cust_125    Germany  04-10-2024         9        1765      0.04  1152.0   15249.60
34      Keyboard  Accessories  Cust_280         UK  15-08-2024         8        1143      0.00   772.0    9144.00
35       Monitor  Accessories   Cust_88         UK  02-04-2024         5         486      0.04   273.0    2332.80
36      Keyboard  Accessories   Cust_37        USA  29-07-2022         3         451      0.07  1094.0    1258.29
37         Phone       Office   Cust_48      India  12-06-2024         3        1754      0.22   917.0    4104.36
38       Printer  Electronics  Cust_141      India  03-02-2023         7        1679      0.28   331.0    8462.16
39       Printer  Electronics  Cust_241        USA  27-02-2023         9         945      0.01   298.0    8419.95
40        Laptop  Accessories  Cust_180    Germany  24-11-2023         6        1005      0.22  1012.0   47034.00
41       Monitor       Office  Cust_477      India  31-05-2023         5         973       NaN   753.0    4183.90
42    Headphones  Electronics   Cust_17  Australia  01-08-2024         4        1938      0.09   669.0    7054.32
43       Monitor       Office  Cust_139  Australia  11-08-2022         1         794      0.05   128.0     754.30
44    Headphones  Electronics  Cust_176  Australia  25-11-2023         2         865      0.11   369.0    1539.70
45         Mouse  Accessories  Cust_249      India  13-02-2022         6         562      0.15   380.0    2866.20
46         Mouse  Electronics   Cust_52     Canada  11-11-2023         9        1923      0.08   753.0   15922.44
47           NaN       Office  Cust_210     Canada  22-12-2023         4        1370      0.21   976.0    4329.20
48         Mouse  Electronics  Cust_369         UK  25-05-2023         1          54      0.08   235.0      49.68
49    Headphones  Electronics  Cust_232     Canada  30-10-2024         3        1578      0.09   118.0    4307.94
50        Laptop  Accessories   Cust_58      India  23-03-2023         2         382      0.21   613.0     603.56
51         Mouse  Electronics  Cust_376     Canada  03-02-2024         4        1751      0.28  1121.0    5042.88
52         Phone       Office  Cust_326        USA  27-06-2022         1         554      0.22   838.0     432.12
53       Monitor       Office  Cust_487        USA  19-12-2024         1         542      0.14   973.0     466.12
54         Mouse  Accessories  Cust_319     Canada  19-03-2022         9         182      0.15   611.0    1392.30
55       Monitor       Office  Cust_251        USA  12-10-2023         1        1581      0.10   383.0    1422.90
56        Laptop       Office  Cust_332        USA  27-04-2022         9        1011      0.01  1055.0    9008.01
57        Tablet  Accessories  Cust_469      India  03-10-2022         5        1442      0.19  1190.0    5840.10
58    Headphones       Office  Cust_410      India  28-06-2023         6        1532      0.00   912.0    9192.00
59    Headphones  Electronics  Cust_273         UK  20-07-2022         3        1819      0.00  1432.0    5457.00
60       Printer  Accessories   Cust_17    Germany  18-06-2023         1        1977      0.12   905.0    1739.76
61         Phone       Office  Cust_220         UK  21-05-2023         1         596      0.23   727.0     458.92
62         Phone       Office  Cust_404     Canada  11-06-2023         2         159      0.13   409.0     276.66
63       Monitor  Accessories  Cust_100         UK  17-07-2024         9        1465      0.29  1412.0    9361.35
64         Mouse  Electronics   Cust_13    Germany  04-06-2022         4         274      0.04   431.0    1052.16
65       Printer       Office  Cust_392      India  17-09-2024         7         814      0.07   564.0    5299.14
66    Headphones  Electronics   Cust_21    Germany  01-02-2024         8         470      0.00   191.0    3760.00
67        Tablet  Electronics  Cust_287         UK  05-12-2024         7         206      0.27    72.0    1052.66
68    Headphones       Office  Cust_135     Canada  25-01-2023         2        1416      0.02   523.0    2775.36
69      Keyboard  Electronics  Cust_104         UK  24-03-2024         6        1616      0.22  1099.0    7562.88
70         Mouse       Office   Cust_10        USA  28-01-2022         1        1113      0.17   432.0     923.79
71        Laptop  Electronics  Cust_115    Germany  15-07-2022         6        1412      0.27   918.0    6184.56
72         Mouse  Electronics  Cust_165         UK  27-07-2024         7        1221      0.11   677.0    7606.83
73        Tablet  Electronics  Cust_330  Australia  03-10-2023         2        1476      0.26   387.0    2184.48
74        Tablet       Office   Cust_71         UK  10-11-2023         4         918      0.12   465.0    3231.36
75       Printer  Accessories  Cust_200         UK  28-07-2023         1        1717      0.08  1210.0    1579.64
76        Tablet  Electronics  Cust_111  Australia  29-01-2024         8         786       NaN   947.0    4778.88
77    Headphones       Office  Cust_205        USA  08-04-2023         9         293      0.17  1000.0    2188.71
78         Mouse  Accessories  Cust_127  Australia  05-08-2024         6        1066      0.27  1111.0    4669.08
79      Keyboard  Accessories  Cust_363  Australia  08-05-2022         6        1935      0.11  1348.0   10332.90
80       Monitor  Accessories  Cust_373    Germany  01-09-2022         5        1667      0.24   989.0    6334.60
81         Phone       Office  Cust_366    Germany  28-05-2023         8        1318      0.09   896.0    9595.04
82       Monitor       Office  Cust_372     Canada  11-11-2024         7        1374      0.21  1014.0    7598.22
83        Laptop  Accessories   Cust_83  Australia  05-12-2022         4         338      0.09   119.0    1230.32
84         Phone  Accessories   Cust_63        USA  28-04-2024         9         672      0.15   185.0    5140.80
85        Laptop  Accessories    Cust_9  Australia  16-01-2023         7        1458      0.24   828.0   77565.60
86       Monitor       Office  Cust_420        USA  22-03-2023         8        1879      0.18  1043.0   12326.24
87       Monitor       Office   Cust_46      India  22-08-2023         2          81      0.07   439.0     150.66
88      Keyboard       Office  Cust_176  Australia  08-09-2022         7        1740      0.22  1392.0    9500.40
89        Tablet  Accessories  Cust_236         UK  30-03-2022         2        1053      0.29   113.0    1495.26
90      Keyboard  Accessories  Cust_280      India  29-11-2024         5         805      0.05  1475.0    3823.75
91       Monitor  Electronics  Cust_492  Australia  02-06-2024         9         777       NaN   397.0    6013.98
92        Tablet  Accessories  Cust_110    Germany  09-12-2024         7        1630      0.15   607.0    9698.50
93        Laptop  Electronics  Cust_307      India  27-04-2023         9         695      0.04   839.0    6004.80
94       Monitor  Electronics  Cust_437     Canada  17-01-2024         7        1147      0.24   368.0    6102.04
95         Mouse       Office  Cust_161         UK  29-09-2024         1         447      0.28  1257.0     321.84
96         Mouse  Accessories   Cust_22         UK  15-08-2024         2        1083      0.27   187.0    1581.18
97      Keyboard  Accessories   Cust_49    Germany  17-01-2023         4        1255      0.19   172.0    4066.20
98        Tablet  Electronics  Cust_318    Germany  13-02-2022         4        1705      0.17  1165.0    5660.60
99        Laptop  Electronics   Cust_64      India  13-11-2022         8        1803      0.01  1059.0   14279.76
100      Monitor  Accessories  Cust_480      India  14-09-2022         2        1243      0.27  1259.0    1814.78
101      Printer  Electronics  Cust_297  Australia  01-10-2024         2        1664      0.28  1263.0    2396.16
102     Keyboard  Accessories  Cust_456     Canada  17-12-2022         5         212      0.20  1476.0     848.00
103        Phone  Accessories  Cust_407     Canada  08-09-2023         6         342      0.29   525.0    1456.92
104       Tablet       Office  Cust_449      India  17-01-2022         7        1215      0.12   401.0    7484.40
105      Monitor  Electronics  Cust_396  Australia  24-01-2024         7         703      0.10   629.0    4428.90
106        Phone  Electronics  Cust_198    Germany  17-10-2022         6        1178      0.02   773.0    6926.64
107   Headphones       Office  Cust_328     Canada  06-03-2022         7        1253      0.07   147.0    8157.03
108      Monitor  Accessories  Cust_292         UK  20-12-2024         3         424      0.16   377.0    1068.48
109        Mouse       Office  Cust_466        USA  28-01-2023         2        1155      0.18   766.0    1894.20
110        Mouse       Office   Cust_59        USA  17-10-2024         4         781      0.16   733.0    2624.16
111      Monitor       Office  Cust_460     Canada  01-06-2024         2         285      0.27   898.0     416.10
112      Printer  Electronics  Cust_420     Canada  07-05-2022         3         689      0.08   321.0    1901.64
113        Phone       Office  Cust_441  Australia  02-02-2022         8        1755      0.19     NaN   11372.40
114        Mouse       Office  Cust_179     Canada  09-12-2024         5        1973      0.10  1236.0    8878.50
115     Keyboard  Electronics  Cust_350     Canada  09-09-2024         2        1414      0.24  1416.0    2149.28
116      Monitor       Office  Cust_445  Australia  14-01-2024         8         986      0.03   910.0    7651.36
117        Mouse  Electronics  Cust_255  Australia  30-05-2023         5         557      0.10   984.0    2506.50
118      Monitor       Office  Cust_365    Germany  26-03-2022         1        1894      0.22   157.0    1477.32
119        Mouse       Office   Cust_53      India  08-01-2024         2        1013      0.03  1063.0    1965.22
120     Keyboard  Electronics  Cust_364     Canada  27-06-2023         3        1542      0.19   416.0   37470.60
121      Printer       Office   Cust_10      India  28-09-2024         5        1472      0.22   951.0    5740.80
122      Printer  Electronics  Cust_495  Australia  14-10-2022         6         367      0.01   302.0    2179.98
123        Mouse  Accessories  Cust_267     Canada  03-03-2022         9        1236      0.12   450.0    9789.12
124      Printer       Office  Cust_228      India  12-06-2022         2        1869      0.09   264.0    3401.58
125   Headphones  Accessories  Cust_444        USA  06-10-2024         3         145      0.20   798.0     348.00
126       Tablet  Electronics  Cust_324      India  11-12-2023         7        1100      0.17   677.0    6391.00
127   Headphones       Office   Cust_21         UK  10-12-2022         1         110      0.27   815.0      80.30
128   Headphones       Office  Cust_441     Canada  10-05-2022         1         786      0.21   161.0     620.94
129      Printer  Accessories   Cust_28    Germany  15-06-2024         3         104      0.29  1155.0     221.52
130        Phone  Electronics  Cust_457    Germany  11-04-2023         6        1433      0.13   334.0    7480.26
131      Monitor  Accessories   Cust_75    Germany  23-05-2023         8         556      0.24  1217.0    3380.48
132      Monitor       Office  Cust_281    Germany  07-08-2022         1        1206      0.17  1260.0    1000.98
133   Headphones  Electronics  Cust_359  Australia  21-07-2023         3        1134      0.00   354.0    3402.00
134        Mouse  Electronics  Cust_409    Germany  02-11-2024         2         215       NaN   713.0     309.60
135       Laptop  Electronics  Cust_355        USA  13-05-2023         4         573      0.18   305.0    1879.44
136       Tablet       Office  Cust_427  Australia  27-01-2024         5        1569      0.07  1128.0    7295.85
137        Mouse  Accessories  Cust_403    Germany  29-07-2022         6         282      0.08   411.0   15566.40
138     Keyboard  Accessories   Cust_77     Canada  25-02-2022         6        1285      0.13   907.0    6707.70
139      Monitor  Accessories  Cust_150         UK  17-01-2024         2         212      0.16   353.0     356.16
140        Phone  Electronics   Cust_82        USA  24-07-2022         1         363      0.13    74.0     315.81
141     Keyboard  Electronics  Cust_366         UK  24-07-2023         3         365      0.27   330.0     799.35
142       Tablet  Electronics  Cust_403    Germany  24-05-2024         6         983       NaN   182.0    4187.58
143        Phone  Electronics  Cust_357    Germany  06-05-2024         8         600      0.24    88.0    3648.00
144      Monitor  Electronics  Cust_393      India  24-05-2022         5        1399      0.09   588.0    6365.45
145       Tablet  Electronics  Cust_286  Australia  03-11-2024         3         211      0.17   945.0     525.39
146       Laptop  Electronics  Cust_168     Canada  29-03-2022         2         634      0.16   869.0    1065.12
147     Keyboard  Electronics  Cust_485        USA  23-11-2024         5        1046      0.10   831.0    4707.00
148       Laptop  Accessories   Cust_22     Canada  27-09-2024         2         606      0.02   617.0    1187.76
149      Monitor  Accessories  Cust_136        USA  17-09-2023         2         115      0.07   752.0     213.90
150     Keyboard       Office  Cust_453      India  16-07-2022         5        1165      0.13    84.0    5067.75
151      Monitor  Electronics    Cust_3     Canada  31-08-2024         8        1609      0.09    86.0   11713.52
152      Monitor       Office  Cust_261     Canada  25-01-2024         9        1762      0.04   432.0   15223.68
153        Phone  Accessories  Cust_449         UK  23-08-2024         3        1641      0.08   287.0    4529.16
154     Keyboard  Electronics  Cust_115      India  10-11-2024         5         905      0.05   139.0    4298.75
155   Headphones       Office   Cust_67      India  05-12-2022         1         589      0.03  1141.0     571.33
156     Keyboard  Accessories   Cust_61      India  05-08-2024         9         757      0.01  1362.0    6744.87
157     Keyboard  Electronics  Cust_439  Australia  16-01-2022         7        1581      0.28  1107.0    7968.24
158       Tablet       Office  Cust_105      India  29-05-2023         8         216      0.28   669.0    1244.16
159   Headphones       Office   Cust_59  Australia  07-09-2024         7        1139      0.10  1083.0    7175.70
160     Keyboard       Office  Cust_181  Australia  21-07-2023         2         793      0.24   607.0    1205.36
161        Mouse       Office   Cust_99    Germany  31-10-2022         7        1962      0.16  1230.0   11536.56
162       Tablet       Office  Cust_195        USA  03-02-2022         4        1426      0.08   465.0    5247.68
163      Monitor  Accessories    Cust_4        USA  27-06-2022         1         378      0.26   600.0     279.72
164      Monitor       Office  Cust_339    Germany  20-07-2023         1        1446      0.28   301.0    1041.12
165        Mouse       Office  Cust_120      India  29-04-2022         6        1810      0.07   213.0   10099.80
166      Monitor  Electronics  Cust_176         UK  12-05-2022         7        1579      0.29   347.0    7847.63
167      Printer  Accessories  Cust_275         UK  09-06-2024         4         749      0.11  1121.0    2666.44
168       Tablet  Electronics  Cust_204        USA  27-11-2023         3        1291      0.20  1079.0    3098.40
169        Phone       Office   Cust_38        USA  20-02-2024         5        1913      0.17    46.0    7938.95
170        Phone  Accessories   Cust_73    Germany  27-11-2023         5        1648      0.25  1046.0    6180.00
171      Printer  Electronics  Cust_229        USA  13-11-2024         1        1534      0.29   213.0    1089.14
172        Phone  Accessories   Cust_44  Australia  15-08-2022         4        1367      0.24  1312.0    4155.68
173        Phone  Electronics  Cust_103      India  22-02-2024         9        1643      0.02   834.0   14491.26

In [259]:
dataset.head()

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32
2,NaN,Electronics,Cust_205,UK,22-10-2024,8,1470,0.22,1040.0,9172.80
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48

In [260]:
dataset.tail()

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00

In [261]:
dataset.describe(include='all')

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales
count,4904,5000,5000,5000,5000,5000.000000,5000.000000,4900.000000,4898.000000,5000.000000
unique,8,3,500,6,1085,NaN,NaN,NaN,NaN,NaN
top,Printer,Accessories,Cust_480,Germany,27-01-2023,NaN,NaN,NaN,NaN,NaN
freq,644,1692,19,878,15,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,4.954800,1025.086200,0.151865,769.012046,4735.041952
std,NaN,NaN,NaN,NaN,NaN,2.554068,560.293526,0.086790,425.539933,6456.650648
min,NaN,NaN,NaN,NaN,NaN,1.000000,50.000000,0.000000,30.000000,40.470000
25%,NaN,NaN,NaN,NaN,NaN,3.000000,535.000000,0.080000,395.250000,1460.025000
50%,NaN,NaN,NaN,NaN,NaN,5.000000,1014.000000,0.150000,774.500000,3406.040000
75%,NaN,NaN,NaN,NaN,NaN,7.000000,1510.250000,0.230000,1132.750000,6553.980000
max,NaN,NaN,NaN,NaN,NaN,9.000000,1999.000000,0.300000,1499.000000,162604.800000

In [262]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Product     4904 non-null   object
 1   Category    5000 non-null   object
 2   Customer    5000 non-null   object
 3   Region      5000 non-null   object
 4   Date        5000 non-null   object
 5   Quantity    5000 non-null   int64
 6   Unit Price  5000 non-null   int64
 7   Discount    4900 non-null   float64
 8   Cost        4898 non-null   float64
 9   Sales       5000 non-null   float64
dtypes: float64(3), int64(2), object(5)
memory usage: 390.8+ KB

In [263]:
dataset.shape

(5000, 10)

In [264]:
dataset.columns

Index(['Product', 'Category', 'Customer', 'Region', 'Date', 'Quantity',
       'Unit Price', 'Discount', 'Cost', 'Sales'],
      dtype='object')

In [265]:
dataset.dtypes

Product        object
Category       object
Customer       object
Region         object
Date           object
Quantity        int64
Unit Price      int64
Discount      float64
Cost          float64
Sales         float64
dtype: object

In [266]:
dataset.isnull().sum()

Product        96
Category        0
Customer        0
Region          0
Date            0
Quantity        0
Unit Price      0
Discount      100
Cost          102
Sales           0
dtype: int64

In [267]:
dataset.dropna(subset=['Product','Cost'], inplace=True)

In [268]:
dataset['Discount']=dataset['Discount'].fillna(0)
dataset['Discount']

0       0.17
1       0.29
3       0.08
4       0.01
5       0.25
        ...
4995    0.08
4996    0.13
4997    0.21
4998    0.17
4999    0.17
Name: Discount, Length: 4803, dtype: float64

In [269]:
dataset.isnull().sum()

Product       0
Category      0
Customer      0
Region        0
Date          0
Quantity      0
Unit Price    0
Discount      0
Cost          0
Sales         0
dtype: int64

In [270]:
dataset.duplicated().sum()

np.int64(90)

In [271]:
# it actually shows the duplicate values
dataset[dataset.duplicated()]

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Cost,Sales
478,Headphones,Electronics,Cust_232,Canada,30-10-2024,3,1578,0.09,118.0,4307.94
612,Keyboard,Office,Cust_9,Australia,09-01-2023,8,1679,0.05,1038.0,12760.40
843,Mouse,Office,Cust_393,Canada,03-01-2024,9,926,0.12,412.0,7333.92
927,Printer,Electronics,Cust_140,Australia,31-05-2023,6,823,0.30,1230.0,3456.60
986,Keyboard,Electronics,Cust_366,UK,24-07-2023,3,365,0.27,330.0,799.35
...,...,...,...,...,...,...,...,...,...,...
4890,Headphones,Office,Cust_452,India,09-04-2023,4,301,0.13,1455.0,1047.48
4896,Printer,Accessories,Cust_395,UK,14-07-2024,4,440,0.28,1365.0,1267.20
4925,Tablet,Electronics,Cust_249,India,05-12-2022,8,864,0.08,458.0,6359.04
4935,Keyboard,Office,Cust_287,Canada,26-12-2024,7,943,0.04,454.0,6336.96
4985,Headphones,Office,Cust_154,Germany,19-01-2022,1,1518,0.07,1188.0,1411.74

In [272]:
dataset.drop_duplicates(inplace=True)

In [273]:
dataset.shape

(4713, 10)

In [274]:
dataset.rename(columns={'Cost':'Produ_Cost'},inplace=True)

In [275]:
dataset.sort_values('Sales',ascending=False)

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales
858,Monitor,Accessories,Cust_474,Germany,12-01-2022,9,1882,0.04,761.0,162604.80
4003,Laptop,Electronics,Cust_53,USA,15-03-2022,7,1935,0.14,1268.0,116487.00
3885,Mouse,Office,Cust_416,India,07-04-2024,7,1696,0.02,694.0,116345.60
4320,Tablet,Electronics,Cust_329,UK,25-06-2022,7,1774,0.00,950.0,115487.40
3610,Monitor,Accessories,Cust_232,USA,09-07-2024,9,1217,0.07,497.0,101862.90
...,...,...,...,...,...,...,...,...,...,...
1157,Printer,Office,Cust_402,UK,29-11-2024,1,70,0.08,267.0,64.40
1125,Headphones,Accessories,Cust_173,Australia,27-06-2023,1,67,0.08,830.0,61.64
48,Mouse,Electronics,Cust_369,UK,25-05-2023,1,54,0.08,235.0,49.68
3028,Phone,Office,Cust_456,Canada,28-03-2022,1,67,0.28,1259.0,48.24
2441,Phone,Accessories,Cust_93,Australia,20-01-2022,1,57,0.29,1244.0,40.47

In [276]:
dataset['Product'].value_counts()

Product
Printer       616
Monitor       614
Laptop        613
Keyboard      590
Phone         584
Tablet        571
Headphones    570
Mouse         555
Name: count, dtype: int64

In [277]:
dataset['Region'].unique()

array(['Canada', 'UK', 'USA', 'Germany', 'Australia', 'India'],
      dtype=object)

In [278]:
dataset['Region'].nunique()

6

In [279]:
dataset.query('Sales>100000')

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales
858,Monitor,Accessories,Cust_474,Germany,12-01-2022,9,1882,0.04,761.0,162604.8
3610,Monitor,Accessories,Cust_232,USA,09-07-2024,9,1217,0.07,497.0,101862.9
3885,Mouse,Office,Cust_416,India,07-04-2024,7,1696,0.02,694.0,116345.6
4003,Laptop,Electronics,Cust_53,USA,15-03-2022,7,1935,0.14,1268.0,116487.0
4320,Tablet,Electronics,Cust_329,UK,25-06-2022,7,1774,0.00,950.0,115487.4

In [280]:
pd.pivot_table(dataset,values='Sales',index='Region',aggfunc=['sum','max'])

                  sum       max
                Sales     Sales
Region
Australia  3650380.00   77565.6
Canada     3555734.70   55855.8
Germany    4030712.96  162604.8
India      3834840.28  116345.6
UK         3547774.58  115487.4
USA        3731854.71  116487.0

In [281]:
dataset_clean = (
    dataset
   .query("Sales > 100000 and Region == 'UK'")
    .assign(Product=lambda x: x["Product"].str.upper())
    .sort_values("Sales", ascending=False)
)
dataset_clean

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales
4320,TABLET,Electronics,Cust_329,UK,25-06-2022,7,1774,0.0,950.0,115487.4

In [282]:
dataset=dataset.assign(
    Profit= lambda x: x['Sales']-x['Produ_Cost']
)

In [283]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales,Profit
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,3714.12
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,5175.32
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40,231.40
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48,206.48
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,8559.75
...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4779.28
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4005.90
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4439.32
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,6447.35
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,5217.00

In [284]:
dataset["Region_Avg_Sales"] = dataset.groupby("Region")["Sales"].transform("mean")
dataset["Region_Avg_Sales"]

0       4395.222126
1       4395.222126
3       4736.681682
4       4395.222126
5       4395.222126
           ...
4995    4395.222126
4996    4741.873837
4997    4644.249364
4998    4644.249364
4999    4736.681682
Name: Region_Avg_Sales, Length: 4713, dtype: float64

In [285]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales,Profit,Region_Avg_Sales
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,3714.12,4395.222126
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,5175.32,4395.222126
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40,231.40,4736.681682
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48,206.48,4395.222126
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,8559.75,4395.222126
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4779.28,4395.222126
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4005.90,4741.873837
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4439.32,4644.249364
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,6447.35,4644.249364
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,5217.00,4736.681682

In [286]:
dataset['Sales_Level']=pd.qcut(dataset['Sales'], q=4,
labels=['Low','Medium','High','Very High'])

In [287]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales,Profit,Region_Avg_Sales,Sales_Level
0,Printer,Electronics,Cust_440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,3714.12,4395.222126,High
1,Printer,Office,Cust_480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,5175.32,4395.222126,High
3,Monitor,Electronics,Cust_336,UK,21-08-2023,5,214,0.08,753.0,984.40,231.40,4736.681682,Low
4,Monitor,Accessories,Cust_440,Canada,17-10-2022,4,213,0.01,637.0,843.48,206.48,4395.222126,Low
5,Headphones,Accessories,Cust_138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,8559.75,4395.222126,Very High
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Cust_336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4779.28,4395.222126,High
4996,Mouse,Electronics,Cust_420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4005.90,4741.873837,High
4997,Tablet,Office,Cust_265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4439.32,4644.249364,High
4998,Keyboard,Electronics,Cust_84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,6447.35,4644.249364,Very High
4999,Monitor,Electronics,Cust_51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,5217.00,4736.681682,High

In [288]:
dataset[(dataset["Sales"] > 100000) & (dataset["Region"] == "India")]

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales,Profit,Region_Avg_Sales,Sales_Level
3885,Mouse,Office,Cust_416,India,07-04-2024,7,1696,0.02,694.0,116345.6,115651.6,5059.156042,Very High

In [289]:
dataset['Customer']=dataset['Customer'].str.replace("Cust_","Customer")
dataset['Customer']

0       Customer440
1       Customer480
3       Customer336
4       Customer440
5       Customer138
           ...
4995    Customer336
4996    Customer420
4997    Customer265
4998     Customer84
4999     Customer51
Name: Customer, Length: 4713, dtype: object

In [290]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales,Profit,Region_Avg_Sales,Sales_Level
0,Printer,Electronics,Customer440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,3714.12,4395.222126,High
1,Printer,Office,Customer480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,5175.32,4395.222126,High
3,Monitor,Electronics,Customer336,UK,21-08-2023,5,214,0.08,753.0,984.40,231.40,4736.681682,Low
4,Monitor,Accessories,Customer440,Canada,17-10-2022,4,213,0.01,637.0,843.48,206.48,4395.222126,Low
5,Headphones,Accessories,Customer138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,8559.75,4395.222126,Very High
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Customer336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4779.28,4395.222126,High
4996,Mouse,Electronics,Customer420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4005.90,4741.873837,High
4997,Tablet,Office,Customer265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4439.32,4644.249364,High
4998,Keyboard,Electronics,Customer84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,6447.35,4644.249364,Very High
4999,Monitor,Electronics,Customer51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,5217.00,4736.681682,High

In [291]:
avg_revenue = dataset.groupby("Product")["Sales"].agg(["mean","sum","max"])
print(avg_revenue)

                   mean         sum       max
Product
Headphones  4532.157053  2583329.52   58664.4
Keyboard    4640.283678  2737767.37   59392.0
Laptop      5037.781142  3088159.84  116487.0
Monitor     4832.701466  2967278.70  162604.8
Mouse       5114.606324  2838606.51  116345.6
Phone       4717.600565  2755078.73   76944.0
Printer     4332.108685  2668578.95   27936.0
Tablet      4750.433643  2712497.61  115487.4

In [292]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales,Profit,Region_Avg_Sales,Sales_Level
0,Printer,Electronics,Customer440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,3714.12,4395.222126,High
1,Printer,Office,Customer480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,5175.32,4395.222126,High
3,Monitor,Electronics,Customer336,UK,21-08-2023,5,214,0.08,753.0,984.40,231.40,4736.681682,Low
4,Monitor,Accessories,Customer440,Canada,17-10-2022,4,213,0.01,637.0,843.48,206.48,4395.222126,Low
5,Headphones,Accessories,Customer138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,8559.75,4395.222126,Very High
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Customer336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4779.28,4395.222126,High
4996,Mouse,Electronics,Customer420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4005.90,4741.873837,High
4997,Tablet,Office,Customer265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4439.32,4644.249364,High
4998,Keyboard,Electronics,Customer84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,6447.35,4644.249364,Very High
4999,Monitor,Electronics,Customer51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,5217.00,4736.681682,High

In [293]:
dataset["Profit_Margin"]=(dataset["Profit"]/dataset["Sales"])*100
dataset["Profit_Margin"]

0       76.310426
1       91.205995
3       23.506705
4       24.479537
5       93.114139
          ...
4995    98.313201
4996    92.645528
4997    87.693390
4998    93.084381
4999    82.704502
Name: Profit_Margin, Length: 4713, dtype: float64

In [294]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales,Profit,Region_Avg_Sales,Sales_Level,Profit_Margin
0,Printer,Electronics,Customer440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,3714.12,4395.222126,High,76.310426
1,Printer,Office,Customer480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,5175.32,4395.222126,High,91.205995
3,Monitor,Electronics,Customer336,UK,21-08-2023,5,214,0.08,753.0,984.40,231.40,4736.681682,Low,23.506705
4,Monitor,Accessories,Customer440,Canada,17-10-2022,4,213,0.01,637.0,843.48,206.48,4395.222126,Low,24.479537
5,Headphones,Accessories,Customer138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,8559.75,4395.222126,Very High,93.114139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Customer336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4779.28,4395.222126,High,98.313201
4996,Mouse,Electronics,Customer420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4005.90,4741.873837,High,92.645528
4997,Tablet,Office,Customer265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4439.32,4644.249364,High,87.693390
4998,Keyboard,Electronics,Customer84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,6447.35,4644.249364,Very High,93.084381
4999,Monitor,Electronics,Customer51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,5217.00,4736.681682,High,82.704502

In [295]:
dataset["Total_Discount"]=dataset["Quantity"]*dataset["Unit Price"]*dataset["Discount"]
dataset["Total_Discount"]

0        996.88
1       2317.68
3         85.60
4          8.52
5       3064.25
         ...
4995     422.72
4996     646.10
4997    1345.68
4998    1418.65
4999    1292.00
Name: Total_Discount, Length: 4713, dtype: float64

In [296]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales,Profit,Region_Avg_Sales,Sales_Level,Profit_Margin,Total_Discount
0,Printer,Electronics,Customer440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,3714.12,4395.222126,High,76.310426,996.88
1,Printer,Office,Customer480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,5175.32,4395.222126,High,91.205995,2317.68
3,Monitor,Electronics,Customer336,UK,21-08-2023,5,214,0.08,753.0,984.40,231.40,4736.681682,Low,23.506705,85.60
4,Monitor,Accessories,Customer440,Canada,17-10-2022,4,213,0.01,637.0,843.48,206.48,4395.222126,Low,24.479537,8.52
5,Headphones,Accessories,Customer138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,8559.75,4395.222126,Very High,93.114139,3064.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Customer336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4779.28,4395.222126,High,98.313201,422.72
4996,Mouse,Electronics,Customer420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4005.90,4741.873837,High,92.645528,646.10
4997,Tablet,Office,Customer265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4439.32,4644.249364,High,87.693390,1345.68
4998,Keyboard,Electronics,Customer84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,6447.35,4644.249364,Very High,93.084381,1418.65
4999,Monitor,Electronics,Customer51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,5217.00,4736.681682,High,82.704502,1292.00

In [297]:
# Total revenue and profit of the each Region
Region_wise=dataset.groupby("Region")[["Sales","Profit"]].sum()
Region_wise

                Sales      Profit
Region
Australia  3650380.00  3054088.00
Canada     3555734.70  2926495.70
Germany    4030712.96  3397016.96
India      3834840.28  3257565.28
UK         3547774.58  2980757.58
USA        3731854.71  3125402.71

In [298]:
high_margin = dataset[dataset['Profit_Margin'] > 20]
high_margin

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales,Profit,Region_Avg_Sales,Sales_Level,Profit_Margin,Total_Discount
0,Printer,Electronics,Customer440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,3714.12,4395.222126,High,76.310426,996.88
1,Printer,Office,Customer480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,5175.32,4395.222126,High,91.205995,2317.68
3,Monitor,Electronics,Customer336,UK,21-08-2023,5,214,0.08,753.0,984.40,231.40,4736.681682,Low,23.506705,85.60
4,Monitor,Accessories,Customer440,Canada,17-10-2022,4,213,0.01,637.0,843.48,206.48,4395.222126,Low,24.479537,8.52
5,Headphones,Accessories,Customer138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,8559.75,4395.222126,Very High,93.114139,3064.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Customer336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4779.28,4395.222126,High,98.313201,422.72
4996,Mouse,Electronics,Customer420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4005.90,4741.873837,High,92.645528,646.10
4997,Tablet,Office,Customer265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4439.32,4644.249364,High,87.693390,1345.68
4998,Keyboard,Electronics,Customer84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,6447.35,4644.249364,Very High,93.084381,1418.65
4999,Monitor,Electronics,Customer51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,5217.00,4736.681682,High,82.704502,1292.00

In [299]:
low_margin = dataset[dataset['Profit_Margin'] < 10]
low_margin

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales,Profit,Region_Avg_Sales,Sales_Level,Profit_Margin,Total_Discount
15,Tablet,Office,Customer29,UK,14-09-2023,2,63,0.08,938.0,115.92,-822.08,4736.681682,Low,-709.178744,10.08
16,Laptop,Electronics,Customer289,USA,11-03-2023,2,674,0.29,1463.0,957.08,-505.92,4741.873837,Low,-52.860785,390.92
18,Phone,Accessories,Customer382,Australia,16-05-2022,7,178,0.01,1151.0,1233.54,82.54,4644.249364,Low,6.691311,12.46
30,Phone,Office,Customer175,Canada,12-12-2022,3,157,0.24,539.0,357.96,-181.04,4395.222126,Low,-50.575483,113.04
48,Mouse,Electronics,Customer369,UK,25-05-2023,1,54,0.08,235.0,49.68,-185.32,4736.681682,Low,-373.027375,4.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4960,Laptop,Office,Customer10,Germany,22-08-2023,3,60,0.05,1022.0,171.00,-851.00,4891.641942,Low,-497.660819,9.00
4971,Laptop,Electronics,Customer279,UK,23-10-2022,2,406,0.11,654.0,722.68,68.68,4736.681682,Low,9.503515,89.32
4972,Tablet,Accessories,Customer189,UK,13-12-2023,3,310,0.08,863.0,855.60,-7.40,4736.681682,Low,-0.864890,74.40
4973,Laptop,Accessories,Customer16,Canada,09-01-2022,2,647,0.21,1304.0,1022.26,-281.74,4395.222126,Low,-27.560503,271.74
4988,Monitor,Accessories,Customer393,USA,06-08-2022,6,317,0.21,1388.0,1502.58,114.58,4741.873837,Medium,7.625551,399.42

In [300]:
dataset

,Product,Category,Customer,Region,Date,Quantity,Unit Price,Discount,Produ_Cost,Sales,Profit,Region_Avg_Sales,Sales_Level,Profit_Margin,Total_Discount
0,Printer,Electronics,Customer440,Canada,18-03-2023,8,733,0.17,1153.0,4867.12,3714.12,4395.222126,High,76.310426,996.88
1,Printer,Office,Customer480,Canada,01-08-2024,4,1998,0.29,499.0,5674.32,5175.32,4395.222126,High,91.205995,2317.68
3,Monitor,Electronics,Customer336,UK,21-08-2023,5,214,0.08,753.0,984.40,231.40,4736.681682,Low,23.506705,85.60
4,Monitor,Accessories,Customer440,Canada,17-10-2022,4,213,0.01,637.0,843.48,206.48,4395.222126,Low,24.479537,8.52
5,Headphones,Accessories,Customer138,Canada,10-01-2023,7,1751,0.25,633.0,9192.75,8559.75,4395.222126,Very High,93.114139,3064.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Keyboard,Accessories,Customer336,Canada,23-10-2024,4,1321,0.08,82.0,4861.28,4779.28,4395.222126,High,98.313201,422.72
4996,Mouse,Electronics,Customer420,USA,12-01-2022,5,994,0.13,318.0,4323.90,4005.90,4741.873837,High,92.645528,646.10
4997,Tablet,Office,Customer265,Australia,01-05-2024,9,712,0.21,623.0,5062.32,4439.32,4644.249364,High,87.693390,1345.68
4998,Keyboard,Electronics,Customer84,Australia,18-02-2023,5,1669,0.17,479.0,6926.35,6447.35,4644.249364,Very High,93.084381,1418.65
4999,Monitor,Electronics,Customer51,UK,03-03-2024,8,950,0.17,1091.0,6308.00,5217.00,4736.681682,High,82.704502,1292.00

In [301]:
from sqlalchemy import create_engine

username = "root"
password = "mysql12"        
host = "localhost"
port = "3306"
database = "project"

# Create MySQL Connection

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Table Name in MySQL
table_name = "retail_data"

# Insert Data into MySQL
dataset.to_sql(table_name, engine, if_exists="replace", index=False)

print("Data loaded successfully into MySQL")

Data loaded successfully into MySQL

In [302]:
dataset.shape

(4713, 15)